### ISSUE TITLE
I came here from Quora

### ISSUE THREAD

**Issue by Vishesh1999** [Ritiek/ama#2]
Hi,I was really happy after reading your answer on Quora and I was curious to know the sources from which you learned computer programming as I was planning to start learning it too.

**Comment by Ritiek** [comment]
I find the best way to learn is by doing things. I recommend you to start with python, it is simple enough to quickly start building things. You can go to https://codecademy.com to learn the basics and then try to apply them in things around yourself. Put your code here so that people can use it if they find it interesting. You can check out more projects on what people are working here and try to help them or modify them to suit yourself. You can always look up to Google for help for just about anything.
